FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and yarn.lock

COPY package.json yarn.lock ./

# Install app dependencies

RUN yarn install

# Bundle app source

COPY . .

EXPOSE 3000

CMD [ "yarn", "start:api" ]
